image: ubuntu:18.04

stages:
  - environment_nosim
  - build_nosim

environment_nosim:
  stage: environment_nosim
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y tzdata
    - apt-get install -y sudo
    - adduser --disabled-password --gecos '' docker
    - adduser docker sudo
    - echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - dpkg-reconfigure --frontend noninteractive tzdata
    - chmod +x setup_cpm_build_environment.sh
    - echo $RTI_LICENSE_KEY > /license.dat
    - ls -alh
    - cat /license.dat
    - sudo ls -alh
    - ls -alh /opt
    - sudo ./setup_cpm_build_environment.sh --license_path=/license.dat --domain_id=100


build:
   stage: build_nosim
   dependencies:
     - environment_nosim
   script:
     - ls -alh /opt
     - ./build_all.bash
