image: ubuntu:18.04

stages:
  - build_nosim

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

build_nosim:
  stage: build_nosim
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y tzdata
    - apt-get install -y sudo
    - adduser --disabled-password --gecos '' docker
    - adduser docker sudo
    - echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - dpkg-reconfigure --frontend noninteractive tzdata
    - chmod +x setup_cpm_build_environment.sh
    - echo $RTI_LICENSE_KEY > /license.dat
    - ls -alh
    - cat /license.dat
    - sudo ls -alh
    - ls -alh /opt
    - git clone git@git.rwth-aachen.de:CPM/Project/Lab/cpm_base.git
#    - sudo ./setup_cpm_build_environment.sh --license_path=/license.dat --domain_id=100 --simulation
#    - ./build_all.bash --simulation
