parameters:
  bool:
    test1:
      value: true
      info: "test value"
  int:
    test3:
      value: 0
      info: "sadf"
    test4:
      value: 199
      info: "test value"
  double:
    test5:
      value: 0.10000000000000001
      info: "test value"
    test6:
      value: 1918829939.9847331
      info: "test value"
    'trajectory_controller/lateral_P_gain': 
      value: 7.0
      info: ""
    'trajectory_controller/lateral_D_gain': 
      value: 4.0
      info: ""
  string:
    test7:
      value: "TEHST@#+-//\\\\??"
      info: "test value"
  ints:
    test8:
      value:
        - 0
        - 200000
      info: "test value"
  doubles:
    test10:
      value:
        - 29342424
      info: "test value"
    test9:
      value:
        - 0.12313213123123123
        - 12932193.540689999
      info: "test value"
