parameters:
  bool:
    {}
  int:
    {}
  double:
    trajectory_controller/lateral_D_gain:
      value: 4
      info: ""
    trajectory_controller/lateral_P_gain:
      value: 7
      info: ""
  string:
    {}
  ints:
    {}
  doubles:
    {}
