parameters:
  bool:
    {}
  uint64_t:
    middleware_period_ms:
      value: 300
      info: "The period with which the middleware calls the HLC, in nanoseconds"
    middleware_period_ns:
      value: 300000000
      info: "The period with which the middleware calls the HLC, in nanoseconds"
  int:
    {}
  double:
    trajectory_controller/lateral_D_gain:
      value: 4
      info: ""
    trajectory_controller/lateral_P_gain:
      value: 7
      info: ""
  string:
    {}
  ints:
    {}
  doubles:
    {}
